# Generated by Django 2.2 on 2022-08-14 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeId', models.AutoField(primary_key=True, serialize=False)),
                ('employeeName', models.CharField(max_length=255)),
                ('dateofJoined', models.DateField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Team')),
            ],
        ),
    ]
